name: Update Github Stats

on:
  schedule:
    - cron: "47 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'npm'

      - name: Install requirements
        run: npm install

      - name: Github Configurations
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull

      - name: Update Template
        run: node updater.js ${{ github.repository_owner }} googledark
        env:
          GHT: ${{ secrets.GHT }}

      - name: Commit and push changes
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Github Stats updated 🎉" && git push)
